version: "3"
services:
  graph-node:
    image: graphprotocol/graph-node
    ports:
      - "8010:8010"  # GraphQL API
      - "8020:8020"  # Admin API
      - "8030:8030"  # IPFS API
      - "8040:8040"  # Metrics
    depends_on:
      - postgres
    environment:
      postgres_host: postgres
      postgres_user: graph
      postgres_pass: letmein
      postgres_db: graph
      ethereum: arbitrum-fork:http://172.17.0.1:8545
      RUST_LOG: info

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: graph
      POSTGRES_PASSWORD: letmein
      POSTGRES_DB: graph
